Task Motor: bit_twiddle.h File Reference
bit_twiddle.h File Reference
#include <avr/io.h>
Functions
void set_bit (volatile uint8_t &, uint8_t)
This function sets/unsets bits.
void set_bit (volatile uint8_t &, uint8_t, uint8_t)
void clear_and_set (volatile uint8_t &, uint8_t)
This function clears a reg and sets one bit high.
Detailed Description
This file declares a function to set/set low a single bit
Revisions:
4-16-2014 Written by EB
License: This file is copyright 2012 by JR Ridgely and released under the Lesser GNU Public License, version 2. It intended for educational use only, but its use is not limited thereto.
Definition in file bit_twiddle.h.
Function Documentation
void clear_and_set (volatile uint8_t & reg, uint8_t bit)
This function clears a reg and sets one bit high.
set all bits low, then set specified bit high
Parameters:
reg the register to change
bit the bit to set high
Definition at line 64 of file bit_twiddle.cpp.
Referenced by task_motor::run().
void set_bit (volatile uint8_t & reg, uint8_t bit)
This function sets/unsets bits.
set the specified register's specified bit to the specified value
Parameters:
reg A register to change
bit which bit in register to change
value what value to change it to (0 or high)
Definition at line 35 of file bit_twiddle.cpp.
Referenced by motor::brake(), motor::motor(), task_motor::run(), and motor::set_power().