Task Motor: task_adc Class Reference
task_adc Class Reference
This task runs ADCs.
#include <task_adc.h>
Public Member Functions
task_adc (const char *, unsigned portBASE_TYPE, size_t, emstream *)
void run (void)
Detailed Description
This task runs ADCs.
An adc object is instantiated. ADC channels can be "turned on/off" via shared data state changes, then their readings can be read from shared data.
Definition at line 41 of file task_adc.h.
Constructor & Destructor Documentation
task_adc::task_adc (const char * a_name, unsigned portBASE_TYPE a_priority, size_t a_stack_size, emstream * p_ser_dev)
This constructor creates a task which controls the brightness of an LED using input from an A/D converter. The main job of this constructor is to call the constructor of parent class (frt_task); the parent's constructor the work.
Parameters:
a_name A character string which will be the name of this task
a_priority The priority at which this task will initially run (default: 0)
a_stack_size The size of this task's stack in bytes (default: configMINIMAL_STACK_SIZE)
p_ser_dev Pointer to a serial device (port, radio, SD card, etc.) which can be used by this task to communicate (default: NULL)
Definition at line 56 of file task_adc.cpp.
Member Function Documentation
void task_adc::run (void)
This method is called once by the RTOS scheduler. Each time around the for (;;) loop, it reads the shared adc settings and, if necessary, sets adc output to the shared data that exposes it to other tasks
Definition at line 73 of file task_adc.cpp.
References adc::read_average(), adc::read_median(), adc::read_once(), shared_adc0_state, shared_adc0_value, shared_adc1_state, shared_adc1_value, shared_adc2_state, shared_adc2_value, shared_adc3_state, and shared_adc3_value.
The documentation for this class was generated from the following files:
task_adc.h
task_adc.cpp