Task Motor: motor Class Reference
motor Class Reference
This class should run a motor driver for an AVR processor.
#include <motor.h>
Public Member Functions
motor (volatile uint8_t *, uint8_t, volatile uint8_t *, uint8_t, uint8_t, uint8_t, volatile uint8_t *, volatile uint16_t *, emstream *=NULL)
This constructor sets up an motor.
void set_power (int16_t)
This function sets the power level for the motor.
void brake (uint16_t)
This function applies damping to the motor to brake.
Protected Attributes
emstream * ptr_to_serial
use this pointer to the serial port for debug info
volatile uint8_t * mc_port_md
volatile uint16_t * ocr_md
uint8_t mc_bit_a_md
uint8_t mc_bit_b_md
Detailed Description
This class should run a motor driver for an AVR processor.
The motor_driver class. contains member data that sets the various bits needed to create the motor driver. Also contains functions for setting the motor power or braking the motor.
Definition at line 43 of file motor.h.
Constructor & Destructor Documentation
motor::motor (volatile uint8_t * pwm_ddr, uint8_t pwm_bit, volatile uint8_t * mc_ddr, uint8_t mc_bit_a, uint8_t mc_bit_b, uint8_t mc_bit_diag, volatile uint8_t * mc_port, volatile uint16_t * ocr, emstream * p_serial_port = NULL)
This constructor sets up an motor.
motor function drives the PWM to the motor. The function set_power() tells the motor how much torque to auint8_tpply. Sets the polarity. The function brake() will apply damping to the motor to stop the motor.
Parameters:
p_serial_port A pointer to the serial port which writes debugging info.
pwm_ddr A pointer to the PWM data direction register
pwm_bit A pointer to the PWM settings bit
mc_ddr A pointer to the motor controller data direction register
mc_bit_a The first motor controller settings bit
mc_bit_b The second motor controller settings bit
mc_bit_diag The motor controller output enable and diagnostic register
mc_port The motor controller port
ocr The compare register for setting the PWM duty cycle
p_serial_port The debug output port
Definition at line 50 of file motor.cpp.
References brake(), and set_bit().
Member Function Documentation
void motor::brake (uint16_t power)
This function applies damping to the motor to brake.
It creates a short between the two leads of the motor. Can vary the strength of damping
Parameters:
power The power of the damping applied to the brake. 0 is freewheeling, 1023 is max damping
Returns:
none
Definition at line 132 of file motor.cpp.
References set_bit().
Referenced by motor(), and task_motor::run().
void motor::set_power (int16_t power)
This function sets the power level for the motor.
positive input drives positive torque and negative drives negative torque
Parameters:
power power level from -1023 to +1023. negative and positive indicate direction of motor spin
Returns:
none
Definition at line 98 of file motor.cpp.
References set_bit().
Referenced by task_motor::run().
The documentation for this class was generated from the following files:
motor.h
motor.cpp