Task Motor: task_motor Class Reference
task_motor Class Reference
This task runs motors.
#include <task_motor.h>
Public Member Functions
task_motor (const char *, unsigned portBASE_TYPE, size_t, emstream *)
void run (void)
Detailed Description
This task runs motors.
Two motor objects are instantiated, then they can be given commands via shared variables that are continuously checked by this motor task
Definition at line 50 of file task_motor.h.
Constructor & Destructor Documentation
task_motor::task_motor (const char * a_name, unsigned portBASE_TYPE a_priority, size_t a_stack_size, emstream * p_ser_dev)
This constructor creates a task which controls motors. The main job of this constructor is to call the constructor of parent class (frt_task); the parent's constructor the work.
Parameters:
a_name A character string which will be the name of this task
a_priority The priority at which this task will initially run (default: 0)
a_stack_size The size of this task's stack in bytes (default: configMINIMAL_STACK_SIZE)
p_ser_dev Pointer to a serial device (port, radio, SD card, etc.) which can be used by this task to communicate (default: NULL)
Definition at line 58 of file task_motor.cpp.
Member Function Documentation
void task_motor::run (void)
This method is called once by the RTOS scheduler. Each time around the for (;;) loop, it reads the shared motor settings and then commands the motors
Definition at line 75 of file task_motor.cpp.
References motor::brake(), clear_and_set(), set_bit(), motor::set_power(), shared_motor1_braking, shared_motor1_power, shared_motor1_state, shared_motor2_braking, shared_motor2_power, and shared_motor2_state.
The documentation for this class was generated from the following files:
task_motor.h
task_motor.cpp