Task Motor: adc Class Reference
adc Class Reference
Public Member Functions
adc (emstream *=NULL)
This constructor sets up an A/D converter.
uint16_t read_once (uint8_t)
This method takes one A/D reading from the given channel and returns it.
uint16_t read_average (uint8_t, uint8_t)
This method takes an average reading on an ADC.
uint16_t read_median (uint8_t, uint8_t)
This method takes a median reading on an ADC.
Protected Attributes
emstream * ptr_to_serial
The ADC class uses this pointer to the serial port to say hello.
Detailed Description
Definition at line 50 of file adc.h.
Constructor & Destructor Documentation
adc::adc (emstream * p_serial_port = NULL)
This constructor sets up an A/D converter.
The A/D is made ready so that when a method such as read_once() or read_oversampled is called, correct A/D conversions can be performed. This is accomplished by enabling the ADC, setting the clock prescaler to "divide-by-32", and setting the analog reference voltage to AVCC with an external capacitor to ground. Input should be a serial port. Successful construction is written to the debug.
Parameters:
p_serial_port A pointer to the serial port which writes debugging info.
Definition at line 67 of file adc.cpp.
References ptr_to_serial.
Member Function Documentation
uint16_t adc::read_average (uint8_t channel, uint8_t samples)
This method takes an average reading on an ADC.
Take an average reading from the adc that is on the channel input as a parameter. The number of samples to be averaged is determined by the parameter "samples". If the "samples" parameter exceeds the maximum permissible number of samples(63), then only 63 samples are taken. The number of samples taken, and the oversampled value are written to the debug stream.
Parameters:
channel
samples
Returns:
adc Value
Definition at line 118 of file adc.cpp.
References read_once().
Referenced by task_adc::run().
uint16_t adc::read_median (uint8_t channel, uint8_t num_samples)
This method takes a median reading on an ADC.
Take a median reading from an array of ADC readings. The number of samples is determined by the parameter "samples". If the "samples" parameter exceeds the maximum permissible number of samples (63), then only 63 samples are taken. The number of samples taken, and the oversampled value are written to the debug stream.
Parameters:
channel
samples
Returns:
adc Value
Definition at line 146 of file adc.cpp.
References compare(), and read_once().
Referenced by task_adc::run().
uint16_t adc::read_once (uint8_t ch)
This method takes one A/D reading from the given channel and returns it.
If the counter reaches a maximum number of cycles of 256, adc will timeout
Parameters:
ch The A/D channel which is being read must be from 0 to 7
Returns:
The result of the A/D conversion
Definition at line 88 of file adc.cpp.
Referenced by operator<<(), read_average(), read_median(), and task_adc::run().
The documentation for this class was generated from the following files:
adc.h
adc.cpp